### ISSUE TITLE
Possible bug in missing value assertions

### ISSUE THREAD

**Issue by smmaurer** [urbansim/orca_test#7]
Just noticed that in my test script, there's an assertion that should fail but does not. [development_tests.py#L96](https://github.com/UDST/orca_test/blob/master/development_tests.py#L96)

Probably minor, but i don't have time to diagnose it right now and wanted to make a note.

**Comment by Eh2406** [comment]
We should convert to using a test runner and continuous integration. add it to the todo list...

**Comment by waddell** [comment]
Right.  We're using TravisCI and Coveralls generally.  Need to get this hooked up.
