### ISSUE TITLE
Add Python 3 cross-compatibility

### ISSUE THREAD

**Issue by smmaurer** [urbansim/orca_test#9]
We should go through and make the Orca_test code cross-compatible with Python 3.3/3.4/3.5 as well as Python 2.7. 

It looks like those are the versions that Orca supports, and this would be best practice anyway.

We might need to rethink the exceptions a bit, but otherwise this shouldn't be too much work. One outstanding question related to that is how to handle passing backtraces along with OrcaAssertionErrors for some of the broader tests (like whether a table/column can be successfully generated). See discussion in #6.

**Comment by sablanchard** [comment]
Addressed in #23
